language: c
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2

_android: &_android
  language: android
  os: linux
  # jdk: oraclejdk8
  sudo: true
  android:
    components:
      - tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
    licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

matrix:
  include:
  - os: osx
    env: BUILD_ENV=ios_arm64 PLATFORM=iphoneos DEPLOY=TEST
    if: NOT tag IS present

  - os: osx
    env: BUILD_ENV=ios_x64 PLATFORM=iphonesimulator DEPLOY=TEST
    if: NOT tag IS present

  - env: BUILD_ENV=android_armv7a ANDROID_ABI=armeabi-v7a NDK=r18b DEPLOY=TEST
    <<: *_android
    if: NOT tag IS present

  - env: BUILD_ENV=android_arm64 ANDROID_ABI=arm64-v8a NDK=r18b DEPLOY=TEST
    <<: *_android
    if: NOT tag IS present

  - env: BUILD_ENV=android_arm64 ANDROID_ABI=x86 NDK=r18b DEPLOY=TEST
    <<: *_android
    if: NOT tag IS present

  - env: BUILD_ENV=android_arm64 ANDROID_ABI=x86_64 NDK=r18b DEPLOY=TEST
    <<: *_android
    if: NOT tag IS present

install:
  - cd /tmp
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget -q https://cmake.org/files/v3.18/cmake-3.18.4-Linux-x86_64.tar.gz;
      tar -xzf cmake-3.18.4-Linux-x86_64.tar.gz;
      export PATH=/tmp/cmake-3.18.4-Linux-x86_64/bin:$PATH;
      wget -q https://dl.google.com/android/repository/android-ndk-${NDK}-linux-x86_64.zip;
      unzip -q android-ndk-${NDK}-linux-x86_64.zip;
      export ANDROID_NDK_HOME=/tmp/android-ndk-${NDK};
    else
      ulimit -c unlimited;
      sudo sysctl kern.corefile=/cores/core;
      easy_install six;
      if [[ "$ANDROID_ABI" != "" ]]; then
        wget -q https://dl.google.com/android/repository/android-ndk-${NDK}-darwin-x86_64.zip;
        unzip -q android-ndk-${NDK}-darwin-x86_64.zip;
        export ANDROID_NDK_HOME=/tmp/android-ndk-${NDK};
      fi
    fi

script:
  - cd $TRAVIS_BUILD_DIR/build
  - export COMMITID=$(git log --format=%h -1)
  - export APPSUFFIX=$(date +'%Y%m%d%H')-$COMMITID
  - export TRAVIS_TAG="version"-$APPSUFFIX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./.build.ios.sh $PLATFORM;
    else
      ./.build.android.sh $ANDROID_ABI;
    fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $USER_NAME
  - git config --local user.email $USER_EMAIL
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: libspvsdk*.tar.gz
  skip_cleanup: true
  on:
    condition: $DEPLOY != ""
    branch: release2github
